# Generated by Django 4.2.1 on 2024-10-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_slug_alter_women_title'),
        ('women', '0004_alter_women_is_published'),
    ]

    operations = [
    ]
