# Generated by Django 4.2.1 on 2024-10-18 21:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_women_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={},
        ),
        migrations.AlterModelManagers(
            name='women',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
