# Generated by Django 4.2.1 on 2024-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_merge_20241017_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='women',
            name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
