# Generated by Django 4.2.1 on 2024-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_women_options_alter_women_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
        ),
    ]
